In [2]:
# Importação de bibliotecas e datasets
import pandas as pd
import requests
import zipfile
import io

pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", 500)
pd.set_option("display.width", 1000)

# Requisição para download do dataset e extração do arquivo
zip_file = "https://archive.ics.uci.edu/static/public/10/automobile.zip"

r = requests.get(zip_file, stream=True)

automobile = zipfile.ZipFile(io.BytesIO(r.content))
automobile.extractall()

In [3]:
# Manipulação dos dados
data = "automobile/imports-85.data"

col_names=[
    "symboling", "normalized-losses", "fuel-type", "aspiration",
    "num-of-doors", "body-style", "drive-wheels", "engine-location",
    "wheel-base", "length", "width", "height", "curb-weight", "engine-type",
    "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke",
    "compression-ratio", "horsepower", "peak-rpm", "city-mpg", "highway-mpg", "price"
]

# Leitura do arquivo CSV e criação do data frame
df_car = pd.read_csv(data, sep=",", names=col_names, na_values="?", header=None)

In [4]:
# Verificando o shape e imprimindo os primeiros registros

df_car.shape
df_car.head(5)

   symboling normalized-losses fuel-type aspiration num-of-doors   body-style drive-wheels engine-location  wheel-base  length  width  height  curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price
3        NaN       alfa-romero       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  13495.0
3        NaN       alfa-romero       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  16500.0
1        NaN       alfa-romero       gas        std          two    hatchback          rwd           front        94.5   171.2   65.5    52.4         2823        ohcv              six          152        mpfi  2.68    3.47                9.0       154.0    5000.0        19           26  16500.0
2      164.0              audi       gas        std         four        sedan          fwd           front        99.8   176.6   66.2    54.3         2337         ohc             four          109        mpfi  3.19    3.40               10.0       102.0    5500.0        24           30  13950.0
2      164.0              audi       gas        std         four        sedan          4wd           front        99.4   176.6   66.4    54.3         2824         ohc             five          136        mpfi  3.19    3.40                8.0       115.0    5500.0        18           22  17450.0

In [5]:
# Exibindo as informações
df_car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 205 entries, 3 to -1
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          164 non-null    float64
 1   normalized-losses  205 non-null    object
 2   fuel-type          205 non-null    object
 3   aspiration         205 non-null    object
 4   num-of-doors       203 non-null    object
 5   body-style         205 non-null    object
 6   drive-wheels       205 non-null    object
 7   engine-location    205 non-null    object
 8   wheel-base         205 non-null    float64
 9   length             205 non-null    float64
 10  width              205 non-null    float64
 11  height             205 non-null    float64
 12  curb-weight        205 non-null    int64
 13  engine-type        205 non-null    object
 14  num-of-cylinders   205 non-null    object
 15  engine-size        205 non-null    int64
 16  fuel-system        205 non-null    object
 17  bore               201 non-null    float64
 18  stroke             201 non-null    float64
 19  compression-ratio  205 non-null    float64
 20  horsepower         203 non-null    float64
 21  peak-rpm           203 non-null    float64
 22  city-mpg           205 non-null    int64
 23  highway-mpg        205 non-null    int64
 24  price              201 non-null    float64
dtypes: float64(11), int64(4), object(10)
memory usage: 41.6+ KB

In [6]:
# Verificando as colunas
df_car.columns

Index(['symboling', 'normalized-losses', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price'], dtype='object')

In [7]:
# Copiando colunas
df_car = df_car[["aspiration", "num-of-doors", "drive-wheels", "num-of-cylinders"]].copy()

In [8]:
# Examinando os dados
df_car.head()

  aspiration num-of-doors drive-wheels num-of-cylinders
3        std          two          rwd             four
3        std          two          rwd             four
1        std          two          rwd              six
2        std         four          fwd             four
2        std         four          4wd             five

In [9]:
# Codificação de componentes
df_car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 205 entries, 3 to -1
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   aspiration        205 non-null    object
 1   num-of-doors      203 non-null    object
 2   drive-wheels      205 non-null    object
 3   num-of-cylinders  205 non-null    object
dtypes: object(4)
memory usage: 8.0+ KB

In [10]:
# Determinando os valores ordinais
df_car["num-of-doors"].value_counts()

num-of-doors
four    114
two      89
Name: count, dtype: int64

In [11]:
# Mapeamento com dicionário
door_mapper = {
    "two": 2,
    "four": 4
}

In [12]:
# Gerando uma nova coluna com base no dicionário criado
df_car["doors"] = df_car["num-of-doors"].replace(door_mapper)

/tmp/ipython-input-1767665560.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_car["doors"] = df_car["num-of-doors"].replace(door_mapper)

In [13]:
# Exibindo o data frame
df_car.head()

  aspiration num-of-doors drive-wheels num-of-cylinders  doors
3        std          two          rwd             four    2.0
3        std          two          rwd             four    2.0
1        std          two          rwd              six    2.0
2        std         four          fwd             four    4.0
2        std         four          4wd             five    4.0

In [16]:
# Gerando novas colunas
df_car["num-of-cylinders"].value_counts()

num-of-cylinders
four      159
six        24
five       11
eight       5
two         4
twelve      1
three       1
Name: count, dtype: int64

In [17]:
# Criando mapeador
cylinder_mapper = {
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "eight": 8,
    "twelve": 12
}

In [18]:
# Mapear com replace
df_car["cylinders"] = df_car["num-of-cylinders"].replace(cylinder_mapper)

/tmp/ipython-input-2020830770.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_car["cylinders"] = df_car["num-of-cylinders"].replace(cylinder_mapper)

In [19]:
# Exibindo o DataFrame
df_car.head()

  aspiration num-of-doors drive-wheels num-of-cylinders  doors  cylinders
3        std          two          rwd             four    2.0          4
3        std          two          rwd             four    2.0          4
1        std          two          rwd              six    2.0          6
2        std         four          fwd             four    4.0          4
2        std         four          4wd             five    4.0          5

In [21]:
# Codificando os dados categóricos não ordinais
df_car["drive-wheels"].value_counts()

drive-wheels
fwd    120
rwd     76
4wd      9
Name: count, dtype: int64

In [22]:
# Adicionando novos componentes
df_car = pd.get_dummies(df_car, columns=["drive-wheels"])

In [23]:
# Exiibindo componentes
df_car.head()

  aspiration num-of-doors num-of-cylinders  doors  cylinders  drive-wheels_4wd  drive-wheels_fwd  drive-wheels_rwd
3        std          two             four    2.0          4             False             False              True
3        std          two             four    2.0          4             False             False              True
1        std          two              six    2.0          6             False             False              True
2        std         four             four    4.0          4             False              True             False
2        std         four             five    4.0          5              True             False             False

In [24]:
# Calculando e exibindo a contagem de frequência
df_car["aspiration"].value_counts()

aspiration
std      168
turbo     37
Name: count, dtype: int64

In [25]:
# Aplicando o One-Hot Encoder
df_car = pd.get_dummies(
    df_car,
    columns=["aspiration"],
    drop_first=True
)

In [26]:
# Visualização do One-Hot Encoder
df_car.head()

  num-of-doors num-of-cylinders  doors  cylinders  drive-wheels_4wd  drive-wheels_fwd  drive-wheels_rwd  aspiration_turbo
3          two             four    2.0          4             False             False              True             False
3          two             four    2.0          4             False             False              True             False
1          two              six    2.0          6             False             False              True             False
2         four             four    4.0          4             False              True             False             False
2         four             five    4.0          5              True             False             False             False